//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.cuentascliente = new HashSet<cuentascliente>();
            this.ordenes = new HashSet<ordenes>();
        }
    
        public int clie_id { get; set; }
        public string clie_idtipoidentificacion { get; set; }
        public string clie_identificacion { get; set; }
        public string clie_nombre { get; set; }
        public string clie_apellidos { get; set; }
        public string clie_direccion { get; set; }
        public string clie_idsexo { get; set; }
        public string clie_telefono { get; set; }
        public string clie_barrio { get; set; }
        public string clie_longitud { get; set; }
        public string clie_latitud { get; set; }
        public string clie_altura { get; set; }
        public string clie_clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuentascliente> cuentascliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenes> ordenes { get; set; }
    }
}
