//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordendetalle
    {
        public int detord_id { get; set; }
        public Nullable<int> detord_idproducto { get; set; }
        public Nullable<int> detord_ordennumero { get; set; }
        public string detord_precio { get; set; }
        public string detord_cantidad { get; set; }
        public string detord_descuento { get; set; }
        public string detord_total { get; set; }
        public string detord_tamano { get; set; }
        public string detord_color { get; set; }
        public string detord_fechaenvio { get; set; }
    
        public virtual ordenes ordenes { get; set; }
        public virtual producto producto { get; set; }
    }
}
