//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordenes()
        {
            this.ordendetalle = new HashSet<ordendetalle>();
        }
    
        public int ord_id { get; set; }
        public string ord_numero { get; set; }
        public Nullable<int> ord_idcliente { get; set; }
        public Nullable<int> ord_idtienda { get; set; }
        public string ord_direccion { get; set; }
        public string ord_fecha { get; set; }
        public string ord_latitud { get; set; }
        public string ord_longitud { get; set; }
        public string ord_altura { get; set; }
        public string ord_fechaenvio { get; set; }
        public Nullable<int> ord_idestado { get; set; }
        public Nullable<double> ord_totalcompra { get; set; }
        public string ord_descripcion { get; set; }
        public Nullable<int> ord_idformapago { get; set; }
        public string detord_pagacon { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estadoorden estadoorden { get; set; }
        public virtual mediopago mediopago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordendetalle> ordendetalle { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
