//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tienda()
        {
            this.ordenes = new HashSet<ordenes>();
            this.producto = new HashSet<producto>();
            this.categoria = new HashSet<categoria>();
        }
    
        public int tien_id { get; set; }
        public string tien_nit { get; set; }
        public string tien_clave { get; set; }
        public string tien_tipoidentificacion { get; set; }
        public string tien_razonsocial { get; set; }
        public string tien_direccion { get; set; }
        public string tien_barrio { get; set; }
        public string tien_telefono { get; set; }
        public string tien_correo { get; set; }
        public string tien_latitud { get; set; }
        public string tien_longitud { get; set; }
        public string tien_altura { get; set; }
        public string tien_facebook { get; set; }
        public string tien_instagram { get; set; }
        public string tien_youtube { get; set; }
        public string tien_foto { get; set; }
        public Nullable<bool> tien_premium { get; set; }
        public string tien_key { get; set; }
        public string tien_privatekey { get; set; }
        public string tien_pkey { get; set; }
        public string tien_idcliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenes> ordenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoria> categoria { get; set; }
    }
}
